spring.application.name=agent-api-relay

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
spring.datasource.url=jdbc:h2:file:./data/agent-db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
#agent.model=gpt-oss-120b
#agent.base-url=http://103.124.72.114:8000/v1/
#agent.apikey=twaitoken
#agent.model=${MODEL}
#agent.base-url=${BASE_URL}
#agent.apikey=${API_KEY}
spring.mvc.async.request-timeout=-1
vm.host=${HOST}
vm.port=${PORT}
vm.drug-path=${DRUG_PATH}
agent.ocr-url=${OCR_URL}
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true